export type EnvType = "string" | "number" | "boolean" | "url" | "email" | "enum" | "json";

export interface FieldSchema {
  type: EnvType;
  required?: boolean;
  default?: string;
  values?: string[];
  secret?: boolean;
  description?: string;
}

export interface EnvSchema {
  $schema?: string;
  name?: string;
  fields: Record<string, FieldSchema>;
}

export interface Issue {
  key: string;
  message: string;
  severity: "error" | "warning";
}

const TRUE = new Set(["1", "true", "yes", "on"]);
const FALSE = new Set(["0", "false", "no", "off"]);

export function coerce(value: string, field: FieldSchema): unknown {
  switch (field.type) {
    case "number": {
      const n = Number(value);
      if (!Number.isFinite(n)) throw new Error("not a number");
      return n;
    }
    case "boolean": {
      const lower = value.toLowerCase();
      if (TRUE.has(lower)) return true;
      if (FALSE.has(lower)) return false;
      throw new Error("not a boolean (use true/false, 1/0, yes/no)");
    }
    case "url": {
      const url = new URL(value);
      if (!/^https?:$/.test(url.protocol)) throw new Error("url must be http(s)");
      return url.toString();
    }
    case "email": {
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) throw new Error("not an email");
      return value;
    }
    case "enum": {
      if (!field.values?.includes(value)) {
        throw new Error(`expected one of: ${(field.values ?? []).join(", ")}`);
      }
      return value;
    }
    case "json": {
      return JSON.parse(value);
    }
    default:
      return value;
  }
}

export function validateEnv(
  env: Record<string, string | undefined>,
  schema: EnvSchema,
): { ok: boolean; values: Record<string, unknown>; issues: Issue[] } {
  const issues: Issue[] = [];
  const values: Record<string, unknown> = {};
  for (const [key, field] of Object.entries(schema.fields)) {
    const raw = env[key] ?? field.default;
    if (raw === undefined || raw === "") {
      if (field.required !== false) {
        issues.push({ key, message: "missing required variable", severity: "error" });
      }
      continue;
    }
    try {
      values[key] = coerce(raw, field);
    } catch (error) {
      issues.push({
        key,
        message: (error as Error).message,
        severity: "error",
      });
    }
  }
  for (const key of Object.keys(env)) {
    if (env[key] === undefined) continue;
    if (!(key in schema.fields) && key.trim()) {
      issues.push({
        key,
        message: "variable is not declared in the schema",
        severity: "warning",
      });
    }
  }
  return { ok: issues.every((i) => i.severity !== "error"), values, issues };
}

export function exampleFromSchema(schema: EnvSchema): string {
  const lines = [
    `# generated by envsentinel — https://github.com/KodYazicam/envsentinel`,
    schema.name ? `# ${schema.name}` : "",
  ].filter(Boolean);
  for (const [key, field] of Object.entries(schema.fields)) {
    if (field.description) lines.push(`# ${field.description}`);
    const placeholder =
      field.default ??
      (field.type === "boolean"
        ? "false"
        : field.type === "number"
          ? "0"
          : field.type === "url"
            ? "https://example.com"
            : field.type === "email"
              ? "dev@example.com"
              : field.type === "enum"
                ? (field.values?.[0] ?? "")
                : field.type === "json"
                  ? "{}"
                  : field.secret
                    ? "change-me"
                    : "");
    lines.push(`${key}=${placeholder}`);
  }
  return `${lines.join("\n")}\n`;
}

export function typesFromSchema(schema: EnvSchema): string {
  const fields = Object.entries(schema.fields)
    .map(([key, field]) => {
      const optional = field.required === false && field.default === undefined;
      const ts = tsType(field);
      const comment = field.description ? `  /** ${field.description} */\n` : "";
      return `${comment}  ${key}${optional ? "?" : ""}: ${ts};`;
    })
    .join("\n");
  return `/* generated by envsentinel — https://github.com/KodYazicam/envsentinel */\nexport interface Env {\n${fields}\n}\n\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv extends Env {}\n  }\n}\nexport {};\n`;
}

function tsType(field: FieldSchema): string {
  switch (field.type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    case "enum":
      return (field.values ?? []).map((v) => JSON.stringify(v)).join(" | ") || "string";
    default:
      return "string";
  }
}
